sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: D04GDqf3LPLeKXQAVlX3YBW4Ysati4
    access-key-id: LTAI5t8MNi3JwodNMWz9sYdG
    bucket-name: java-study-bucket
  redis:
    password: 123456
    database: 0
    port: 6379
    host: localhost
  wechat:
    appid: wx6d722f7864500114
    secret: 90b125786a837323c632bec0c91aae17
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
